# Generated by Django 2.2.1 on 2019-05-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_contacts', '0002_auto_20190528_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adress_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_id',
        ),
        migrations.AddField(
            model_name='adress',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_contacts.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_contacts.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='group_id',
            field=models.ManyToManyField(to='my_contacts.Group'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_contacts.Person'),
        ),
    ]
