# Generated by Django 2.2.1 on 2019-05-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_contacts', '0003_auto_20190529_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='person_id',
        ),
        migrations.AddField(
            model_name='person',
            name='adresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_contacts.Adress'),
        ),
    ]
