# Generated by Django 2.2.1 on 2019-05-29 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_contacts', '0004_auto_20190529_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adresses',
        ),
        migrations.AddField(
            model_name='adress',
            name='person_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_contacts.Person'),
        ),
    ]
