# Generated by Django 2.2.1 on 2019-05-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_contacts', '0005_auto_20190529_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='group_id',
            new_name='group',
        ),
    ]
